### ISSUE TITLE
just need it to trigger on motion

### ISSUE THREAD

**Issue by alanjsims** [MKme/Wemos-D1-ESP8266-PIR-Alarm#3]
hi, great and easy presentation and was setup easily. I get emails from IFTTT about every minute or 2...can the code be changed to only fire on motion? That would be a great help for me.  Also, I have the pot values on the lowest sensitvity on the pir unit but how can i reduce the sensitivity down to about 2 to 3 feet, if possible.  Thanks Alan

**Comment by MKme** [comment]
You have the hardware set up wrong. This already triggers on motion.  Suggest posting in the Arduino forums if you are having PIR problems.

**Comment by alanjsims** [comment]
Hi and thanks...i think i mis-spoke...of course it fires on motion, but it is so sensitive it seems to fire even when the wind blows in a different direction, so it seems as if the sensor sends endless emails...my question now,  more clearly, is how to reduce the PIR sensitivity after I have turned the little green gauges all the way to their minimum.  thanks Alan
