### ISSUE TITLE
Motion fires every 20 seconds

### ISSUE THREAD

**Issue by gweeds30** [MKme/Wemos-D1-ESP8266-PIR-Alarm#4]
Hi, new to this. I like the code and the concept. I am having an issue though, it seems to fire off every 20 seconds. I see there is a 20000 delay in the code to avoid spamming emails, but when i plug it in it runs every 20s anyway. any thoughts?

Thanks

**Comment by MKme** [comment]
You have a hardware problem with your sensor/wiring etc. You need to work through that. Lots of tutorials out there or suggest Arduino forum.
